import type { PreviewCssPalette } from "./tweakcn-preview";

type Scale = {
	bg: string;
	fg: string;
	card: string;
	primary: string;
	primaryFg: string;
	muted: string;
	mutedFg: string;
	accent: string;
	accentFg: string;
	border: string;
	input: string;
	ring: string;
};

function fromScale(s: Scale): PreviewCssPalette {
	return {
		background: s.bg,
		foreground: s.fg,
		card: s.card,
		cardForeground: s.fg,
		popover: s.card,
		popoverForeground: s.fg,
		primary: s.primary,
		primaryForeground: s.primaryFg,
		secondary: s.muted,
		secondaryForeground: s.fg,
		muted: s.muted,
		mutedForeground: s.mutedFg,
		accent: s.accent,
		accentForeground: s.accentFg,
		destructive: "#dc2626",
		destructiveForeground: "#ffffff",
		border: s.border,
		input: s.input,
		ring: s.ring,
	};
}

/** Approximate shadcn-style neutral + semantic scales when no tweakcn registry theme applies. */
const SCALES: Record<string, Scale> = {
	zinc: {
		bg: "#fafafa",
		fg: "#18181b",
		card: "#ffffff",
		primary: "#18181b",
		primaryFg: "#fafafa",
		muted: "#f4f4f5",
		mutedFg: "#71717a",
		accent: "#f4f4f5",
		accentFg: "#18181b",
		border: "#e4e4e7",
		input: "#ffffff",
		ring: "#18181b",
	},
	neutral: {
		bg: "#fafafa",
		fg: "#171717",
		card: "#ffffff",
		primary: "#171717",
		primaryFg: "#fafafa",
		muted: "#f5f5f5",
		mutedFg: "#737373",
		accent: "#f5f5f5",
		accentFg: "#171717",
		border: "#e5e5e5",
		input: "#ffffff",
		ring: "#171717",
	},
	stone: {
		bg: "#fafaf9",
		fg: "#1c1917",
		card: "#ffffff",
		primary: "#57534e",
		primaryFg: "#fafaf9",
		muted: "#f5f5f4",
		mutedFg: "#78716c",
		accent: "#f5f5f4",
		accentFg: "#1c1917",
		border: "#e7e5e4",
		input: "#ffffff",
		ring: "#57534e",
	},
	slate: {
		bg: "#f8fafc",
		fg: "#0f172a",
		card: "#ffffff",
		primary: "#334155",
		primaryFg: "#f8fafc",
		muted: "#f1f5f9",
		mutedFg: "#64748b",
		accent: "#e2e8f0",
		accentFg: "#0f172a",
		border: "#e2e8f0",
		input: "#ffffff",
		ring: "#334155",
	},
	gray: {
		bg: "#f9fafb",
		fg: "#111827",
		card: "#ffffff",
		primary: "#374151",
		primaryFg: "#f9fafb",
		muted: "#f3f4f6",
		mutedFg: "#6b7280",
		accent: "#e5e7eb",
		accentFg: "#111827",
		border: "#e5e7eb",
		input: "#ffffff",
		ring: "#374151",
	},
	red: {
		bg: "#fef2f2",
		fg: "#450a0a",
		card: "#ffffff",
		primary: "#dc2626",
		primaryFg: "#ffffff",
		muted: "#fee2e2",
		mutedFg: "#991b1b",
		accent: "#fecaca",
		accentFg: "#450a0a",
		border: "#fecaca",
		input: "#ffffff",
		ring: "#dc2626",
	},
	rose: {
		bg: "#fff1f2",
		fg: "#4c0519",
		card: "#ffffff",
		primary: "#e11d48",
		primaryFg: "#ffffff",
		muted: "#ffe4e6",
		mutedFg: "#9f1239",
		accent: "#fecdd3",
		accentFg: "#4c0519",
		border: "#fecdd3",
		input: "#ffffff",
		ring: "#e11d48",
	},
	orange: {
		bg: "#fff7ed",
		fg: "#431407",
		card: "#ffffff",
		primary: "#ea580c",
		primaryFg: "#ffffff",
		muted: "#ffedd5",
		mutedFg: "#9a3412",
		accent: "#fed7aa",
		accentFg: "#431407",
		border: "#fed7aa",
		input: "#ffffff",
		ring: "#ea580c",
	},
	amber: {
		bg: "#fffbeb",
		fg: "#451a03",
		card: "#ffffff",
		primary: "#d97706",
		primaryFg: "#ffffff",
		muted: "#fef3c7",
		mutedFg: "#92400e",
		accent: "#fde68a",
		accentFg: "#451a03",
		border: "#fde68a",
		input: "#ffffff",
		ring: "#d97706",
	},
	yellow: {
		bg: "#fefce8",
		fg: "#422006",
		card: "#ffffff",
		primary: "#ca8a04",
		primaryFg: "#ffffff",
		muted: "#fef9c3",
		mutedFg: "#854d0e",
		accent: "#fef08a",
		accentFg: "#422006",
		border: "#fef08a",
		input: "#ffffff",
		ring: "#ca8a04",
	},
	lime: {
		bg: "#f7fee7",
		fg: "#1a2e05",
		card: "#ffffff",
		primary: "#65a30d",
		primaryFg: "#ffffff",
		muted: "#ecfccb",
		mutedFg: "#3f6212",
		accent: "#d9f99d",
		accentFg: "#1a2e05",
		border: "#d9f99d",
		input: "#ffffff",
		ring: "#65a30d",
	},
	green: {
		bg: "#f0fdf4",
		fg: "#052e16",
		card: "#ffffff",
		primary: "#16a34a",
		primaryFg: "#ffffff",
		muted: "#dcfce7",
		mutedFg: "#166534",
		accent: "#bbf7d0",
		accentFg: "#052e16",
		border: "#bbf7d0",
		input: "#ffffff",
		ring: "#16a34a",
	},
	emerald: {
		bg: "#ecfdf5",
		fg: "#022c22",
		card: "#ffffff",
		primary: "#059669",
		primaryFg: "#ffffff",
		muted: "#d1fae5",
		mutedFg: "#047857",
		accent: "#a7f3d0",
		accentFg: "#022c22",
		border: "#a7f3d0",
		input: "#ffffff",
		ring: "#059669",
	},
	teal: {
		bg: "#f0fdfa",
		fg: "#042f2e",
		card: "#ffffff",
		primary: "#0d9488",
		primaryFg: "#ffffff",
		muted: "#ccfbf1",
		mutedFg: "#0f766e",
		accent: "#99f6e4",
		accentFg: "#042f2e",
		border: "#99f6e4",
		input: "#ffffff",
		ring: "#0d9488",
	},
	cyan: {
		bg: "#ecfeff",
		fg: "#083344",
		card: "#ffffff",
		primary: "#0891b2",
		primaryFg: "#ffffff",
		muted: "#cffafe",
		mutedFg: "#0e7490",
		accent: "#a5f3fc",
		accentFg: "#083344",
		border: "#a5f3fc",
		input: "#ffffff",
		ring: "#0891b2",
	},
	sky: {
		bg: "#f0f9ff",
		fg: "#0c4a6e",
		card: "#ffffff",
		primary: "#0284c7",
		primaryFg: "#ffffff",
		muted: "#e0f2fe",
		mutedFg: "#0369a1",
		accent: "#bae6fd",
		accentFg: "#0c4a6e",
		border: "#bae6fd",
		input: "#ffffff",
		ring: "#0284c7",
	},
	blue: {
		bg: "#eff6ff",
		fg: "#1e3a8a",
		card: "#ffffff",
		primary: "#2563eb",
		primaryFg: "#ffffff",
		muted: "#dbeafe",
		mutedFg: "#1d4ed8",
		accent: "#bfdbfe",
		accentFg: "#1e3a8a",
		border: "#bfdbfe",
		input: "#ffffff",
		ring: "#2563eb",
	},
	indigo: {
		bg: "#eef2ff",
		fg: "#312e81",
		card: "#ffffff",
		primary: "#4f46e5",
		primaryFg: "#ffffff",
		muted: "#e0e7ff",
		mutedFg: "#4338ca",
		accent: "#c7d2fe",
		accentFg: "#312e81",
		border: "#c7d2fe",
		input: "#ffffff",
		ring: "#4f46e5",
	},
	violet: {
		bg: "#f5f3ff",
		fg: "#4c1d95",
		card: "#ffffff",
		primary: "#7c3aed",
		primaryFg: "#ffffff",
		muted: "#ede9fe",
		mutedFg: "#6d28d9",
		accent: "#ddd6fe",
		accentFg: "#4c1d95",
		border: "#ddd6fe",
		input: "#ffffff",
		ring: "#7c3aed",
	},
	purple: {
		bg: "#faf5ff",
		fg: "#581c87",
		card: "#ffffff",
		primary: "#9333ea",
		primaryFg: "#ffffff",
		muted: "#f3e8ff",
		mutedFg: "#7e22ce",
		accent: "#e9d5ff",
		accentFg: "#581c87",
		border: "#e9d5ff",
		input: "#ffffff",
		ring: "#9333ea",
	},
	fuchsia: {
		bg: "#fdf4ff",
		fg: "#701a75",
		card: "#ffffff",
		primary: "#c026d3",
		primaryFg: "#ffffff",
		muted: "#fae8ff",
		mutedFg: "#a21caf",
		accent: "#f0abfc",
		accentFg: "#701a75",
		border: "#f0abfc",
		input: "#ffffff",
		ring: "#c026d3",
	},
};

const FALLBACK_MAP: Record<string, PreviewCssPalette> = Object.fromEntries(
	Object.entries(SCALES).map(([k, v]) => [k, fromScale(v)]),
);

export function getFallbackPreviewPalette(
	baseColor: string,
): PreviewCssPalette {
	return FALLBACK_MAP[baseColor] ?? FALLBACK_MAP.zinc;
}
